In [1]:


import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [19]:
#implementation of framework of target net and evaluation net
class Net(nn.Module):
    def __init__(self, action_num, feature_num):
        super(Net, self).__init__()
        #the first fully connect layer
        self.fc1 = nn.Linear(feature_num, 20)
        #randomly initialize the fc layer
        self.fc1.weight.data.normal_(0,0.1)
        #drop out layer 1
        self.drop1 = nn.Dropout(0.2)
        # the second fully connect layer
        self.fc2 = nn.Linear(20, 10)
        # randomly initialize the fc layer
        self.fc2.weight.data.normal_(0, 0.1)
        # drop out layer 1
        self.drop1 = nn.Dropout(0.1)
        #out_layer
        self.out = nn.Linear(10, action_num)
        self.out.weight.data.normal_(0,0.1)
        #forward function in pytorch module
    def forward(self,x):
        #first layer
        x = self.fc1(x)
        x = self.drop1(x)
        x = F.relu(x)
        #second layer
        x = self.fc2(x)
        x = self.drop1(x)
        x = F.relu(x)
        #output layer
        actions_value = self.out(x)
        return actions_value

In [20]:
actions_value = torch.randn((4,1))
print(actions_value)
print(torch.max(actions_value, 1)[1])

tensor([[ 0.9987],
        [-0.4181],
        [ 2.4053],
        [-0.1450]])
tensor([0, 0, 0, 0])


In [90]:
eval_net = Net(4,10)
# x = range(10)
# x = torch.unsqueeze(torch.FloatTensor(x), 0)
# print(x)

x = np.random.randn(3,10)
y = 3
#y = torch.FloatTensor(y)
x = torch.FloatTensor(x)
print(x)
#print(y.shape)
m1 = eval_net.forward(x)
print(m1)
print(m1.max(1)[0])
print(y*m1.max(1)[0])
print((y*m1.max(1)[0].view(3,1)).shape)

tensor([[-0.9901, -0.7676,  0.6552,  0.7930, -0.4817, -0.1406,  1.0469, -1.2071,
          1.0672, -0.3268],
        [-1.0680,  0.3523,  0.4588, -0.8255,  1.2473, -0.0325, -0.1333, -1.5066,
          1.1580, -1.1426],
        [-0.8098, -1.1565,  0.3280, -0.6830, -0.3359,  0.0410, -0.5079,  0.5716,
          0.0954,  1.0933]])
tensor([[-0.1159, -0.1256,  0.0221, -0.2131],
        [-0.1424, -0.1184,  0.0534, -0.2163],
        [-0.1364, -0.1250,  0.0483, -0.1920]], grad_fn=<AddmmBackward>)
tensor([0.0221, 0.0534, 0.0483], grad_fn=<MaxBackward0>)
tensor([0.0664, 0.1603, 0.1449], grad_fn=<MulBackward0>)
torch.Size([3, 1])


In [54]:
print(torch.sort(m1,1,descending = True)[1].data.numpy()[0] )
x = torch.sort(m1,1,descending = True)[1].data.numpy()[0]
type(x)

[1 3 0 2]


numpy.ndarray

In [57]:
action_sort = []
b  = [3,2]
for i in range(4):
    if (x[i] in b):
        action_sort.append(x[i])
action = action_sort[0]
print(action)

3


In [64]:
a = torch.max(m1,1)[1].data.numpy()
print(a)

[1]


In [41]:
np.random.choice(range(100))

4

In [1]:
a = (2,5)
b = []
c = [(2,5)]
b = list(a)
b.extend(list(c[0]))
b.extend([1])
print(b)

AttributeError: 'NoneType' object has no attribute 'extend'

In [94]:
a = torch.arange(16).view((4,4))
print(a)
b = a.max(1)
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


torch.return_types.max(
values=tensor([ 3,  7, 11, 15]),
indices=tensor([3, 3, 3, 3]))